### ISSUE TITLE
Rotate table lesson/bechmark

### ISSUE THREAD

**Issue by ppKrauss** [zopyx/css-paged-media-tutorial#4]
In [journal](https://en.wikipedia.org/wiki/Scientific_journal) production a typical need is to rotate not only a box, but a whole table structure (HTML `table` tag using `thead`, etc.). A big table that not fit to  portrait orientation (ex. A4 vertical page)  must be rotated  (90 degree) to fit with less compression in  landscape orientation.

For rendering tools, rotate-table algorithm is not the same thing that rotate a single `div` box,  so a benchmark will test the specialized algorithms.

PS: to enhance [lesson-css-transformations](https://www.print-css.rocks/lesson-css-transformations.html) a div box with internal float figure (as a text with lateral thumbnail) may be test better the rendering tools.

**Comment by zopyx** [comment]
Rotating content or floating  rotated content to a new page is a hairy topic. In particular there is no standard and actually only Antennahouse provides some support for dealing with such usecases. However this is not completely doable out-of-the-box with Antennahouse. We've developed a solution for floating arbitrary element to a new page (respected left/right orientation) which is build on of the the AH areatree.
