### ISSUE TITLE
Compliance table with a percentual counter

### ISSUE THREAD

**Issue by ppKrauss** [zopyx/css-paged-media-tutorial#5]
At [Compliance](https://www.print-css.rocks/compliance.html) results, a percentual counter.

Example, at INTRO section PDFreactor, PrinceXML, and Antennahouse was 100%, but Vivliostyle was 11/17=65%.

**Comment by zopyx** [comment]
I don't claim having compliance tests...any percentage numbers would claim an official testing suite which it is not. And the tests are far from being complete and in some cases the specs are ambigious regaring the expected result.

**Comment by zopyx** [comment]
Closing
